### ISSUE TITLE
Naming Suggestions

### ISSUE THREAD

**Issue by ApolloZhu** [dscatuw/GitStarted#6]
These are a few potential changes that can make GitHub pages easier to access:

- rename repo to “GitStarted” so GitHub pages can generate at `dscatuw.github.io/GitStarted`
   - Workshop can be mentioned in topics and in repo description
- rename “Workshop Slides” to just “slides”
   - potentially adding an index.html that redirects to the slides?
- rename “Commands and references” to either “references” or “docs” (or other single word equivalents?
   - potentially adding a README.md in that folder with a “table of contents” for all the documents?
- for each document inside references, consider lowercase, and using dash to separate words? E.g. “pulling-and-pushing” is probably more common in URLs

**Comment by dsc-at-uw** [comment]
- [X] rename repo to “GitStarted”
- [X] rename “Workshop Slides” to just “slides”
- [X] add an index.html
- [X] rename “Commands and references” to "docs"
- [X] use lowercases and dash to separate words for documents under /references
